name: Continuos Integration

on: push

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1

      - name: Use compiler
        run: gcc src/main.c -o main.out
      
      - name: Run executable
        run: |
          cd src
          ./main.out